# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# Block Designs: bd/PCB_All_SRAM/PCB_All_SRAM.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_All_SRAM || ORIG_REF_NAME==PCB_All_SRAM} -quiet] -quiet

# IP: bd/PCB_All_SRAM/ip/PCB_All_SRAM_BF_formatter_0_0/PCB_All_SRAM_BF_formatter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_All_SRAM_BF_formatter_0_0 || ORIG_REF_NAME==PCB_All_SRAM_BF_formatter_0_0} -quiet] -quiet

# IP: bd/PCB_All_SRAM/ip/PCB_All_SRAM_GNSS_Fetcher_mod_0_0/PCB_All_SRAM_GNSS_Fetcher_mod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_All_SRAM_GNSS_Fetcher_mod_0_0 || ORIG_REF_NAME==PCB_All_SRAM_GNSS_Fetcher_mod_0_0} -quiet] -quiet

# IP: bd/PCB_All_SRAM/ip/PCB_All_SRAM_GNSS_Sender_0_0/PCB_All_SRAM_GNSS_Sender_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_All_SRAM_GNSS_Sender_0_0 || ORIG_REF_NAME==PCB_All_SRAM_GNSS_Sender_0_0} -quiet] -quiet

# IP: bd/PCB_All_SRAM/ip/PCB_All_SRAM_HK_formatter_0_0/PCB_All_SRAM_HK_formatter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_All_SRAM_HK_formatter_0_0 || ORIG_REF_NAME==PCB_All_SRAM_HK_formatter_0_0} -quiet] -quiet

# IP: bd/PCB_All_SRAM/ip/PCB_All_SRAM_HTR_CALC_0_0/PCB_All_SRAM_HTR_CALC_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_All_SRAM_HTR_CALC_0_0 || ORIG_REF_NAME==PCB_All_SRAM_HTR_CALC_0_0} -quiet] -quiet

# IP: bd/PCB_All_SRAM/ip/PCB_All_SRAM_I2C_full_sensor_data_0_0/PCB_All_SRAM_I2C_full_sensor_data_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_All_SRAM_I2C_full_sensor_data_0_0 || ORIG_REF_NAME==PCB_All_SRAM_I2C_full_sensor_data_0_0} -quiet] -quiet

# IP: bd/PCB_All_SRAM/ip/PCB_All_SRAM_I2Cmod_0_0/PCB_All_SRAM_I2Cmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_All_SRAM_I2Cmod_0_0 || ORIG_REF_NAME==PCB_All_SRAM_I2Cmod_0_0} -quiet] -quiet

# IP: bd/PCB_All_SRAM/ip/PCB_All_SRAM_Mode_control_0_0/PCB_All_SRAM_Mode_control_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_All_SRAM_Mode_control_0_0 || ORIG_REF_NAME==PCB_All_SRAM_Mode_control_0_0} -quiet] -quiet

# IP: bd/PCB_All_SRAM/ip/PCB_All_SRAM_Pulse_Per_Second_100_0_0/PCB_All_SRAM_Pulse_Per_Second_100_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_All_SRAM_Pulse_Per_Second_100_0_0 || ORIG_REF_NAME==PCB_All_SRAM_Pulse_Per_Second_100_0_0} -quiet] -quiet

# IP: bd/PCB_All_SRAM/ip/PCB_All_SRAM_RAD_formatter_0_0/PCB_All_SRAM_RAD_formatter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_All_SRAM_RAD_formatter_0_0 || ORIG_REF_NAME==PCB_All_SRAM_RAD_formatter_0_0} -quiet] -quiet

# IP: bd/PCB_All_SRAM/ip/PCB_All_SRAM_Read_8SRAM_100MHZ_0_0/PCB_All_SRAM_Read_8SRAM_100MHZ_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_All_SRAM_Read_8SRAM_100MHZ_0_0 || ORIG_REF_NAME==PCB_All_SRAM_Read_8SRAM_100MHZ_0_0} -quiet] -quiet

# IP: bd/PCB_All_SRAM/ip/PCB_All_SRAM_RESTART_mod_0_0/PCB_All_SRAM_RESTART_mod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_All_SRAM_RESTART_mod_0_0 || ORIG_REF_NAME==PCB_All_SRAM_RESTART_mod_0_0} -quiet] -quiet

# IP: bd/PCB_All_SRAM/ip/PCB_All_SRAM_RW_ROUTER_100MHZ_0_0/PCB_All_SRAM_RW_ROUTER_100MHZ_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_All_SRAM_RW_ROUTER_100MHZ_0_0 || ORIG_REF_NAME==PCB_All_SRAM_RW_ROUTER_100MHZ_0_0} -quiet] -quiet

# IP: bd/PCB_All_SRAM/ip/PCB_All_SRAM_SAY_HEY_switchmod_0_0/PCB_All_SRAM_SAY_HEY_switchmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_All_SRAM_SAY_HEY_switchmod_0_0 || ORIG_REF_NAME==PCB_All_SRAM_SAY_HEY_switchmod_0_0} -quiet] -quiet

# IP: bd/PCB_All_SRAM/ip/PCB_All_SRAM_SET_RTC_switchmod_0_0/PCB_All_SRAM_SET_RTC_switchmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_All_SRAM_SET_RTC_switchmod_0_0 || ORIG_REF_NAME==PCB_All_SRAM_SET_RTC_switchmod_0_0} -quiet] -quiet

# IP: bd/PCB_All_SRAM/ip/PCB_All_SRAM_TC_distributor_0_0/PCB_All_SRAM_TC_distributor_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_All_SRAM_TC_distributor_0_0 || ORIG_REF_NAME==PCB_All_SRAM_TC_distributor_0_0} -quiet] -quiet

# IP: bd/PCB_All_SRAM/ip/PCB_All_SRAM_TM_packet_sender_0_0/PCB_All_SRAM_TM_packet_sender_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_All_SRAM_TM_packet_sender_0_0 || ORIG_REF_NAME==PCB_All_SRAM_TM_packet_sender_0_0} -quiet] -quiet

# IP: bd/PCB_All_SRAM/ip/PCB_All_SRAM_UART_RX_100MHZ_0_0/PCB_All_SRAM_UART_RX_100MHZ_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_All_SRAM_UART_RX_100MHZ_0_0 || ORIG_REF_NAME==PCB_All_SRAM_UART_RX_100MHZ_0_0} -quiet] -quiet

# IP: bd/PCB_All_SRAM/ip/PCB_All_SRAM_UART_RX_100MHZ_1_0/PCB_All_SRAM_UART_RX_100MHZ_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_All_SRAM_UART_RX_100MHZ_1_0 || ORIG_REF_NAME==PCB_All_SRAM_UART_RX_100MHZ_1_0} -quiet] -quiet

# IP: bd/PCB_All_SRAM/ip/PCB_All_SRAM_UART_TX_100MHZ_0_0/PCB_All_SRAM_UART_TX_100MHZ_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_All_SRAM_UART_TX_100MHZ_0_0 || ORIG_REF_NAME==PCB_All_SRAM_UART_TX_100MHZ_0_0} -quiet] -quiet

# IP: bd/PCB_All_SRAM/ip/PCB_All_SRAM_Write_8SRAM_100MHZ_0_0/PCB_All_SRAM_Write_8SRAM_100MHZ_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_All_SRAM_Write_8SRAM_100MHZ_0_0 || ORIG_REF_NAME==PCB_All_SRAM_Write_8SRAM_100MHZ_0_0} -quiet] -quiet

# IP: bd/PCB_All_SRAM/ip/PCB_All_SRAM_BF_Data_Collector_Dr_0_0/PCB_All_SRAM_BF_Data_Collector_Dr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_All_SRAM_BF_Data_Collector_Dr_0_0 || ORIG_REF_NAME==PCB_All_SRAM_BF_Data_Collector_Dr_0_0} -quiet] -quiet

# IP: bd/PCB_All_SRAM/ip/PCB_All_SRAM_UART_RX_100MHZ_2_0/PCB_All_SRAM_UART_RX_100MHZ_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_All_SRAM_UART_RX_100MHZ_2_0 || ORIG_REF_NAME==PCB_All_SRAM_UART_RX_100MHZ_2_0} -quiet] -quiet

# IP: bd/PCB_All_SRAM/ip/PCB_All_SRAM_Read_8SRAM_100MHZ_1_0/PCB_All_SRAM_Read_8SRAM_100MHZ_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_All_SRAM_Read_8SRAM_100MHZ_1_0 || ORIG_REF_NAME==PCB_All_SRAM_Read_8SRAM_100MHZ_1_0} -quiet] -quiet

# IP: bd/PCB_All_SRAM/ip/PCB_All_SRAM_Write_8SRAM_100MHZ_1_0/PCB_All_SRAM_Write_8SRAM_100MHZ_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_All_SRAM_Write_8SRAM_100MHZ_1_0 || ORIG_REF_NAME==PCB_All_SRAM_Write_8SRAM_100MHZ_1_0} -quiet] -quiet

# IP: bd/PCB_All_SRAM/ip/PCB_All_SRAM_RW_ROUTER_100MHZ_1_0/PCB_All_SRAM_RW_ROUTER_100MHZ_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_All_SRAM_RW_ROUTER_100MHZ_1_0 || ORIG_REF_NAME==PCB_All_SRAM_RW_ROUTER_100MHZ_1_0} -quiet] -quiet

# IP: bd/PCB_All_SRAM/ip/PCB_All_SRAM_Pulse_WithDelay_Per_0_0/PCB_All_SRAM_Pulse_WithDelay_Per_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_All_SRAM_Pulse_WithDelay_Per_0_0 || ORIG_REF_NAME==PCB_All_SRAM_Pulse_WithDelay_Per_0_0} -quiet] -quiet

# IP: bd/PCB_All_SRAM/ip/PCB_All_SRAM_I2C_HTR_TEMP_0_0/PCB_All_SRAM_I2C_HTR_TEMP_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_All_SRAM_I2C_HTR_TEMP_0_0 || ORIG_REF_NAME==PCB_All_SRAM_I2C_HTR_TEMP_0_0} -quiet] -quiet

# IP: bd/PCB_All_SRAM/ip/PCB_All_SRAM_HTR_ROUTER_0_0/PCB_All_SRAM_HTR_ROUTER_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_All_SRAM_HTR_ROUTER_0_0 || ORIG_REF_NAME==PCB_All_SRAM_HTR_ROUTER_0_0} -quiet] -quiet

# IP: bd/PCB_All_SRAM/ip/PCB_All_SRAM_I2C_HTR_ROUTER_0_0/PCB_All_SRAM_I2C_HTR_ROUTER_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_All_SRAM_I2C_HTR_ROUTER_0_0 || ORIG_REF_NAME==PCB_All_SRAM_I2C_HTR_ROUTER_0_0} -quiet] -quiet

# IP: bd/PCB_All_SRAM/ip/PCB_All_SRAM_HTR_controller_new_0_0/PCB_All_SRAM_HTR_controller_new_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_All_SRAM_HTR_controller_new_0_0 || ORIG_REF_NAME==PCB_All_SRAM_HTR_controller_new_0_0} -quiet] -quiet

# IP: bd/PCB_All_SRAM/ip/PCB_All_SRAM_HTR_controller_new_1_0/PCB_All_SRAM_HTR_controller_new_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_All_SRAM_HTR_controller_new_1_0 || ORIG_REF_NAME==PCB_All_SRAM_HTR_controller_new_1_0} -quiet] -quiet

# XDC: c:/GitHub/GLITCH-Software/FPGA/PCB/PCB_All_SRAM/PCB_All_SRAM.gen/sources_1/bd/PCB_All_SRAM/PCB_All_SRAM_ooc.xdc
