# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# Block Designs: bd/BK_HK_Combined_Test1/BK_HK_Combined_Test1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BK_HK_Combined_Test1 || ORIG_REF_NAME==BK_HK_Combined_Test1} -quiet] -quiet

# IP: bd/BK_HK_Combined_Test1/ip/BK_HK_Combined_Test1_BF_Data_Collector_Dr_0_0/BK_HK_Combined_Test1_BF_Data_Collector_Dr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BK_HK_Combined_Test1_BF_Data_Collector_Dr_0_0 || ORIG_REF_NAME==BK_HK_Combined_Test1_BF_Data_Collector_Dr_0_0} -quiet] -quiet

# IP: bd/BK_HK_Combined_Test1/ip/BK_HK_Combined_Test1_BF_formatter_0_0/BK_HK_Combined_Test1_BF_formatter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BK_HK_Combined_Test1_BF_formatter_0_0 || ORIG_REF_NAME==BK_HK_Combined_Test1_BF_formatter_0_0} -quiet] -quiet

# IP: bd/BK_HK_Combined_Test1/ip/BK_HK_Combined_Test1_GNSS_Fetcher_mod_0_0/BK_HK_Combined_Test1_GNSS_Fetcher_mod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BK_HK_Combined_Test1_GNSS_Fetcher_mod_0_0 || ORIG_REF_NAME==BK_HK_Combined_Test1_GNSS_Fetcher_mod_0_0} -quiet] -quiet

# IP: bd/BK_HK_Combined_Test1/ip/BK_HK_Combined_Test1_GNSS_Sender_0_0/BK_HK_Combined_Test1_GNSS_Sender_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BK_HK_Combined_Test1_GNSS_Sender_0_0 || ORIG_REF_NAME==BK_HK_Combined_Test1_GNSS_Sender_0_0} -quiet] -quiet

# IP: bd/BK_HK_Combined_Test1/ip/BK_HK_Combined_Test1_HK_formatter_0_0/BK_HK_Combined_Test1_HK_formatter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BK_HK_Combined_Test1_HK_formatter_0_0 || ORIG_REF_NAME==BK_HK_Combined_Test1_HK_formatter_0_0} -quiet] -quiet

# IP: bd/BK_HK_Combined_Test1/ip/BK_HK_Combined_Test1_I2C_full_sensor_data_0_0/BK_HK_Combined_Test1_I2C_full_sensor_data_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BK_HK_Combined_Test1_I2C_full_sensor_data_0_0 || ORIG_REF_NAME==BK_HK_Combined_Test1_I2C_full_sensor_data_0_0} -quiet] -quiet

# IP: bd/BK_HK_Combined_Test1/ip/BK_HK_Combined_Test1_I2Cmod_0_0/BK_HK_Combined_Test1_I2Cmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BK_HK_Combined_Test1_I2Cmod_0_0 || ORIG_REF_NAME==BK_HK_Combined_Test1_I2Cmod_0_0} -quiet] -quiet

# IP: bd/BK_HK_Combined_Test1/ip/BK_HK_Combined_Test1_Read6_0_0/BK_HK_Combined_Test1_Read6_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BK_HK_Combined_Test1_Read6_0_0 || ORIG_REF_NAME==BK_HK_Combined_Test1_Read6_0_0} -quiet] -quiet

# IP: bd/BK_HK_Combined_Test1/ip/BK_HK_Combined_Test1_RW_ROUTER4_0_0/BK_HK_Combined_Test1_RW_ROUTER4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BK_HK_Combined_Test1_RW_ROUTER4_0_0 || ORIG_REF_NAME==BK_HK_Combined_Test1_RW_ROUTER4_0_0} -quiet] -quiet

# IP: bd/BK_HK_Combined_Test1/ip/BK_HK_Combined_Test1_Switchmod_0_0/BK_HK_Combined_Test1_Switchmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BK_HK_Combined_Test1_Switchmod_0_0 || ORIG_REF_NAME==BK_HK_Combined_Test1_Switchmod_0_0} -quiet] -quiet

# IP: bd/BK_HK_Combined_Test1/ip/BK_HK_Combined_Test1_TM_packet_sender_0_0/BK_HK_Combined_Test1_TM_packet_sender_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BK_HK_Combined_Test1_TM_packet_sender_0_0 || ORIG_REF_NAME==BK_HK_Combined_Test1_TM_packet_sender_0_0} -quiet] -quiet

# IP: bd/BK_HK_Combined_Test1/ip/BK_HK_Combined_Test1_UART_RXmod_0_0/BK_HK_Combined_Test1_UART_RXmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BK_HK_Combined_Test1_UART_RXmod_0_0 || ORIG_REF_NAME==BK_HK_Combined_Test1_UART_RXmod_0_0} -quiet] -quiet

# IP: bd/BK_HK_Combined_Test1/ip/BK_HK_Combined_Test1_UART_TXmod_0_0/BK_HK_Combined_Test1_UART_TXmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BK_HK_Combined_Test1_UART_TXmod_0_0 || ORIG_REF_NAME==BK_HK_Combined_Test1_UART_TXmod_0_0} -quiet] -quiet

# IP: bd/BK_HK_Combined_Test1/ip/BK_HK_Combined_Test1_Write6_0_0/BK_HK_Combined_Test1_Write6_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BK_HK_Combined_Test1_Write6_0_0 || ORIG_REF_NAME==BK_HK_Combined_Test1_Write6_0_0} -quiet] -quiet

# XDC: c:/GitHub/GLITCH-Software/FPGA/BIG PICTURE STUFF/BF_and_HK_Test1/BF_and_HK_Test1.gen/sources_1/bd/BK_HK_Combined_Test1/BK_HK_Combined_Test1_ooc.xdc
