# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# Block Designs: bd/PCB_Test1/PCB_Test1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_Test1 || ORIG_REF_NAME==PCB_Test1} -quiet] -quiet

# IP: bd/PCB_Test1/ip/PCB_Test1_BF_Data_Collector_Dr_0_0/PCB_Test1_BF_Data_Collector_Dr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_Test1_BF_Data_Collector_Dr_0_0 || ORIG_REF_NAME==PCB_Test1_BF_Data_Collector_Dr_0_0} -quiet] -quiet

# IP: bd/PCB_Test1/ip/PCB_Test1_BF_formatter_0_0/PCB_Test1_BF_formatter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_Test1_BF_formatter_0_0 || ORIG_REF_NAME==PCB_Test1_BF_formatter_0_0} -quiet] -quiet

# IP: bd/PCB_Test1/ip/PCB_Test1_GNSS_Fetcher_mod_0_0/PCB_Test1_GNSS_Fetcher_mod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_Test1_GNSS_Fetcher_mod_0_0 || ORIG_REF_NAME==PCB_Test1_GNSS_Fetcher_mod_0_0} -quiet] -quiet

# IP: bd/PCB_Test1/ip/PCB_Test1_GNSS_Sender_0_0/PCB_Test1_GNSS_Sender_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_Test1_GNSS_Sender_0_0 || ORIG_REF_NAME==PCB_Test1_GNSS_Sender_0_0} -quiet] -quiet

# IP: bd/PCB_Test1/ip/PCB_Test1_HK_formatter_0_0/PCB_Test1_HK_formatter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_Test1_HK_formatter_0_0 || ORIG_REF_NAME==PCB_Test1_HK_formatter_0_0} -quiet] -quiet

# IP: bd/PCB_Test1/ip/PCB_Test1_I2C_full_sensor_data_0_0/PCB_Test1_I2C_full_sensor_data_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_Test1_I2C_full_sensor_data_0_0 || ORIG_REF_NAME==PCB_Test1_I2C_full_sensor_data_0_0} -quiet] -quiet

# IP: bd/PCB_Test1/ip/PCB_Test1_I2Cmod_0_0/PCB_Test1_I2Cmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_Test1_I2Cmod_0_0 || ORIG_REF_NAME==PCB_Test1_I2Cmod_0_0} -quiet] -quiet

# IP: bd/PCB_Test1/ip/PCB_Test1_Pulse_Per_Second_100_0_0/PCB_Test1_Pulse_Per_Second_100_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_Test1_Pulse_Per_Second_100_0_0 || ORIG_REF_NAME==PCB_Test1_Pulse_Per_Second_100_0_0} -quiet] -quiet

# IP: bd/PCB_Test1/ip/PCB_Test1_Read1_100MHZ_0_0/PCB_Test1_Read1_100MHZ_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_Test1_Read1_100MHZ_0_0 || ORIG_REF_NAME==PCB_Test1_Read1_100MHZ_0_0} -quiet] -quiet

# IP: bd/PCB_Test1/ip/PCB_Test1_RW_ROUTER_100MHZ_0_0/PCB_Test1_RW_ROUTER_100MHZ_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_Test1_RW_ROUTER_100MHZ_0_0 || ORIG_REF_NAME==PCB_Test1_RW_ROUTER_100MHZ_0_0} -quiet] -quiet

# IP: bd/PCB_Test1/ip/PCB_Test1_Switchmod_0_0/PCB_Test1_Switchmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_Test1_Switchmod_0_0 || ORIG_REF_NAME==PCB_Test1_Switchmod_0_0} -quiet] -quiet

# IP: bd/PCB_Test1/ip/PCB_Test1_TM_packet_sender_0_0/PCB_Test1_TM_packet_sender_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_Test1_TM_packet_sender_0_0 || ORIG_REF_NAME==PCB_Test1_TM_packet_sender_0_0} -quiet] -quiet

# IP: bd/PCB_Test1/ip/PCB_Test1_UART_RX_100MHZ_0_0/PCB_Test1_UART_RX_100MHZ_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_Test1_UART_RX_100MHZ_0_0 || ORIG_REF_NAME==PCB_Test1_UART_RX_100MHZ_0_0} -quiet] -quiet

# IP: bd/PCB_Test1/ip/PCB_Test1_UART_TX_100MHZ_0_0/PCB_Test1_UART_TX_100MHZ_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_Test1_UART_TX_100MHZ_0_0 || ORIG_REF_NAME==PCB_Test1_UART_TX_100MHZ_0_0} -quiet] -quiet

# IP: bd/PCB_Test1/ip/PCB_Test1_Write1_100MHZ_0_0/PCB_Test1_Write1_100MHZ_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_Test1_Write1_100MHZ_0_0 || ORIG_REF_NAME==PCB_Test1_Write1_100MHZ_0_0} -quiet] -quiet

# IP: bd/PCB_Test1/ip/PCB_Test1_UART_RX_100MHZ_1_0/PCB_Test1_UART_RX_100MHZ_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_Test1_UART_RX_100MHZ_1_0 || ORIG_REF_NAME==PCB_Test1_UART_RX_100MHZ_1_0} -quiet] -quiet

# IP: bd/PCB_Test1/ip/PCB_Test1_TC_distributor_0_0/PCB_Test1_TC_distributor_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCB_Test1_TC_distributor_0_0 || ORIG_REF_NAME==PCB_Test1_TC_distributor_0_0} -quiet] -quiet

# XDC: c:/GitHub/GLITCH-Software/FPGA/PCB/PCB_Test1/PCB_Test1.gen/sources_1/bd/PCB_Test1/PCB_Test1_ooc.xdc
