# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# Block Designs: bd/loop_test/loop_test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==loop_test || ORIG_REF_NAME==loop_test} -quiet] -quiet

# IP: bd/loop_test/ip/loop_test_RW_ROUTER4_0_0/loop_test_RW_ROUTER4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==loop_test_RW_ROUTER4_0_0 || ORIG_REF_NAME==loop_test_RW_ROUTER4_0_0} -quiet] -quiet

# IP: bd/loop_test/ip/loop_test_Switchmod_0_0/loop_test_Switchmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==loop_test_Switchmod_0_0 || ORIG_REF_NAME==loop_test_Switchmod_0_0} -quiet] -quiet

# IP: bd/loop_test/ip/loop_test_UART_TXmod_0_0/loop_test_UART_TXmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==loop_test_UART_TXmod_0_0 || ORIG_REF_NAME==loop_test_UART_TXmod_0_0} -quiet] -quiet

# IP: bd/loop_test/ip/loop_test_Read555_0_0/loop_test_Read555_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==loop_test_Read555_0_0 || ORIG_REF_NAME==loop_test_Read555_0_0} -quiet] -quiet

# IP: bd/loop_test/ip/loop_test_Write555_0_0/loop_test_Write555_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==loop_test_Write555_0_0 || ORIG_REF_NAME==loop_test_Write555_0_0} -quiet] -quiet

# XDC: c:/GitHub/GLITCH-Software/FPGA/SRAM TESTING/SRAM_Breadboard_Test5/SRAM_Breadboard_Test5.gen/sources_1/bd/loop_test/loop_test_ooc.xdc
