# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# Block Designs: bd/BF_Test2/BF_Test2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BF_Test2 || ORIG_REF_NAME==BF_Test2} -quiet] -quiet

# IP: bd/BF_Test2/ip/BF_Test2_BF_Data_Collector_Dr_0_0/BF_Test2_BF_Data_Collector_Dr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BF_Test2_BF_Data_Collector_Dr_0_0 || ORIG_REF_NAME==BF_Test2_BF_Data_Collector_Dr_0_0} -quiet] -quiet

# IP: bd/BF_Test2/ip/BF_Test2_BF_formatter_0_0/BF_Test2_BF_formatter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BF_Test2_BF_formatter_0_0 || ORIG_REF_NAME==BF_Test2_BF_formatter_0_0} -quiet] -quiet

# IP: bd/BF_Test2/ip/BF_Test2_I2C_full_sensor_data_0_0/BF_Test2_I2C_full_sensor_data_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BF_Test2_I2C_full_sensor_data_0_0 || ORIG_REF_NAME==BF_Test2_I2C_full_sensor_data_0_0} -quiet] -quiet

# IP: bd/BF_Test2/ip/BF_Test2_I2Cmod_0_0/BF_Test2_I2Cmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BF_Test2_I2Cmod_0_0 || ORIG_REF_NAME==BF_Test2_I2Cmod_0_0} -quiet] -quiet

# IP: bd/BF_Test2/ip/BF_Test2_Pulse_Per_Second_0_0/BF_Test2_Pulse_Per_Second_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BF_Test2_Pulse_Per_Second_0_0 || ORIG_REF_NAME==BF_Test2_Pulse_Per_Second_0_0} -quiet] -quiet

# IP: bd/BF_Test2/ip/BF_Test2_Read7_0_0/BF_Test2_Read7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BF_Test2_Read7_0_0 || ORIG_REF_NAME==BF_Test2_Read7_0_0} -quiet] -quiet

# IP: bd/BF_Test2/ip/BF_Test2_RW_ROUTER4_0_0/BF_Test2_RW_ROUTER4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BF_Test2_RW_ROUTER4_0_0 || ORIG_REF_NAME==BF_Test2_RW_ROUTER4_0_0} -quiet] -quiet

# IP: bd/BF_Test2/ip/BF_Test2_TM_packet_sender_0_0/BF_Test2_TM_packet_sender_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BF_Test2_TM_packet_sender_0_0 || ORIG_REF_NAME==BF_Test2_TM_packet_sender_0_0} -quiet] -quiet

# IP: bd/BF_Test2/ip/BF_Test2_UART_TXmod_0_0/BF_Test2_UART_TXmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BF_Test2_UART_TXmod_0_0 || ORIG_REF_NAME==BF_Test2_UART_TXmod_0_0} -quiet] -quiet

# IP: bd/BF_Test2/ip/BF_Test2_Write7_0_0/BF_Test2_Write7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BF_Test2_Write7_0_0 || ORIG_REF_NAME==BF_Test2_Write7_0_0} -quiet] -quiet

# IP: bd/BF_Test2/ip/BF_Test2_Switchmod_0_0/BF_Test2_Switchmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BF_Test2_Switchmod_0_0 || ORIG_REF_NAME==BF_Test2_Switchmod_0_0} -quiet] -quiet

# XDC: c:/GitHub/GLITCH-Software/FPGA/SRAM TESTING/SRAM_Breadboard_Test7/SRAM_Breadboard_Test7.gen/sources_1/bd/BF_Test2/BF_Test2_ooc.xdc
