# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# Block Designs: bd/Fpga_and_MCU_Test1/Fpga_and_MCU_Test1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Fpga_and_MCU_Test1 || ORIG_REF_NAME==Fpga_and_MCU_Test1} -quiet] -quiet

# IP: bd/Fpga_and_MCU_Test1/ip/Fpga_and_MCU_Test1_BF_Data_Collector_Dr_0_0/Fpga_and_MCU_Test1_BF_Data_Collector_Dr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Fpga_and_MCU_Test1_BF_Data_Collector_Dr_0_0 || ORIG_REF_NAME==Fpga_and_MCU_Test1_BF_Data_Collector_Dr_0_0} -quiet] -quiet

# IP: bd/Fpga_and_MCU_Test1/ip/Fpga_and_MCU_Test1_BF_formatter_0_0/Fpga_and_MCU_Test1_BF_formatter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Fpga_and_MCU_Test1_BF_formatter_0_0 || ORIG_REF_NAME==Fpga_and_MCU_Test1_BF_formatter_0_0} -quiet] -quiet

# IP: bd/Fpga_and_MCU_Test1/ip/Fpga_and_MCU_Test1_GNSS_Fetcher_mod_0_0/Fpga_and_MCU_Test1_GNSS_Fetcher_mod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Fpga_and_MCU_Test1_GNSS_Fetcher_mod_0_0 || ORIG_REF_NAME==Fpga_and_MCU_Test1_GNSS_Fetcher_mod_0_0} -quiet] -quiet

# IP: bd/Fpga_and_MCU_Test1/ip/Fpga_and_MCU_Test1_GNSS_Sender_0_0/Fpga_and_MCU_Test1_GNSS_Sender_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Fpga_and_MCU_Test1_GNSS_Sender_0_0 || ORIG_REF_NAME==Fpga_and_MCU_Test1_GNSS_Sender_0_0} -quiet] -quiet

# IP: bd/Fpga_and_MCU_Test1/ip/Fpga_and_MCU_Test1_HK_formatter_0_0/Fpga_and_MCU_Test1_HK_formatter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Fpga_and_MCU_Test1_HK_formatter_0_0 || ORIG_REF_NAME==Fpga_and_MCU_Test1_HK_formatter_0_0} -quiet] -quiet

# IP: bd/Fpga_and_MCU_Test1/ip/Fpga_and_MCU_Test1_I2C_full_sensor_data_0_0/Fpga_and_MCU_Test1_I2C_full_sensor_data_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Fpga_and_MCU_Test1_I2C_full_sensor_data_0_0 || ORIG_REF_NAME==Fpga_and_MCU_Test1_I2C_full_sensor_data_0_0} -quiet] -quiet

# IP: bd/Fpga_and_MCU_Test1/ip/Fpga_and_MCU_Test1_I2Cmod_0_0/Fpga_and_MCU_Test1_I2Cmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Fpga_and_MCU_Test1_I2Cmod_0_0 || ORIG_REF_NAME==Fpga_and_MCU_Test1_I2Cmod_0_0} -quiet] -quiet

# IP: bd/Fpga_and_MCU_Test1/ip/Fpga_and_MCU_Test1_Pulse_Per_Second_0_0/Fpga_and_MCU_Test1_Pulse_Per_Second_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Fpga_and_MCU_Test1_Pulse_Per_Second_0_0 || ORIG_REF_NAME==Fpga_and_MCU_Test1_Pulse_Per_Second_0_0} -quiet] -quiet

# IP: bd/Fpga_and_MCU_Test1/ip/Fpga_and_MCU_Test1_Read7_0_0/Fpga_and_MCU_Test1_Read7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Fpga_and_MCU_Test1_Read7_0_0 || ORIG_REF_NAME==Fpga_and_MCU_Test1_Read7_0_0} -quiet] -quiet

# IP: bd/Fpga_and_MCU_Test1/ip/Fpga_and_MCU_Test1_RW_ROUTER4_0_0/Fpga_and_MCU_Test1_RW_ROUTER4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Fpga_and_MCU_Test1_RW_ROUTER4_0_0 || ORIG_REF_NAME==Fpga_and_MCU_Test1_RW_ROUTER4_0_0} -quiet] -quiet

# IP: bd/Fpga_and_MCU_Test1/ip/Fpga_and_MCU_Test1_Switchmod_0_0/Fpga_and_MCU_Test1_Switchmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Fpga_and_MCU_Test1_Switchmod_0_0 || ORIG_REF_NAME==Fpga_and_MCU_Test1_Switchmod_0_0} -quiet] -quiet

# IP: bd/Fpga_and_MCU_Test1/ip/Fpga_and_MCU_Test1_TM_packet_sender_0_0/Fpga_and_MCU_Test1_TM_packet_sender_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Fpga_and_MCU_Test1_TM_packet_sender_0_0 || ORIG_REF_NAME==Fpga_and_MCU_Test1_TM_packet_sender_0_0} -quiet] -quiet

# IP: bd/Fpga_and_MCU_Test1/ip/Fpga_and_MCU_Test1_UART_RXmod_0_0/Fpga_and_MCU_Test1_UART_RXmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Fpga_and_MCU_Test1_UART_RXmod_0_0 || ORIG_REF_NAME==Fpga_and_MCU_Test1_UART_RXmod_0_0} -quiet] -quiet

# IP: bd/Fpga_and_MCU_Test1/ip/Fpga_and_MCU_Test1_UART_TXmod_0_0/Fpga_and_MCU_Test1_UART_TXmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Fpga_and_MCU_Test1_UART_TXmod_0_0 || ORIG_REF_NAME==Fpga_and_MCU_Test1_UART_TXmod_0_0} -quiet] -quiet

# IP: bd/Fpga_and_MCU_Test1/ip/Fpga_and_MCU_Test1_Write7_0_0/Fpga_and_MCU_Test1_Write7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Fpga_and_MCU_Test1_Write7_0_0 || ORIG_REF_NAME==Fpga_and_MCU_Test1_Write7_0_0} -quiet] -quiet

# IP: bd/Fpga_and_MCU_Test1/ip/Fpga_and_MCU_Test1_TC_distributor_0_0/Fpga_and_MCU_Test1_TC_distributor_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Fpga_and_MCU_Test1_TC_distributor_0_0 || ORIG_REF_NAME==Fpga_and_MCU_Test1_TC_distributor_0_0} -quiet] -quiet

# IP: bd/Fpga_and_MCU_Test1/ip/Fpga_and_MCU_Test1_UART_RXmod_1_0/Fpga_and_MCU_Test1_UART_RXmod_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Fpga_and_MCU_Test1_UART_RXmod_1_0 || ORIG_REF_NAME==Fpga_and_MCU_Test1_UART_RXmod_1_0} -quiet] -quiet

# XDC: c:/GitHub/GLITCH-Software/FPGA/BIG PICTURE STUFF/FPGA_to_MCU_Test1/FPGA_to_MCU_Test1.gen/sources_1/bd/Fpga_and_MCU_Test1/Fpga_and_MCU_Test1_ooc.xdc
