# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# Block Designs: bd/testwith1speed/testwith1speed.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testwith1speed || ORIG_REF_NAME==testwith1speed} -quiet] -quiet

# IP: bd/testwith1speed/ip/testwith1speed_BF_Data_Collector_Dr_0_0/testwith1speed_BF_Data_Collector_Dr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testwith1speed_BF_Data_Collector_Dr_0_0 || ORIG_REF_NAME==testwith1speed_BF_Data_Collector_Dr_0_0} -quiet] -quiet

# IP: bd/testwith1speed/ip/testwith1speed_BF_formatter_0_0/testwith1speed_BF_formatter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testwith1speed_BF_formatter_0_0 || ORIG_REF_NAME==testwith1speed_BF_formatter_0_0} -quiet] -quiet

# IP: bd/testwith1speed/ip/testwith1speed_GNSS_Fetcher_mod_0_0/testwith1speed_GNSS_Fetcher_mod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testwith1speed_GNSS_Fetcher_mod_0_0 || ORIG_REF_NAME==testwith1speed_GNSS_Fetcher_mod_0_0} -quiet] -quiet

# IP: bd/testwith1speed/ip/testwith1speed_GNSS_Sender_0_0/testwith1speed_GNSS_Sender_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testwith1speed_GNSS_Sender_0_0 || ORIG_REF_NAME==testwith1speed_GNSS_Sender_0_0} -quiet] -quiet

# IP: bd/testwith1speed/ip/testwith1speed_HK_formatter_0_0/testwith1speed_HK_formatter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testwith1speed_HK_formatter_0_0 || ORIG_REF_NAME==testwith1speed_HK_formatter_0_0} -quiet] -quiet

# IP: bd/testwith1speed/ip/testwith1speed_I2C_full_sensor_data_0_0/testwith1speed_I2C_full_sensor_data_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testwith1speed_I2C_full_sensor_data_0_0 || ORIG_REF_NAME==testwith1speed_I2C_full_sensor_data_0_0} -quiet] -quiet

# IP: bd/testwith1speed/ip/testwith1speed_I2Cmod_0_0/testwith1speed_I2Cmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testwith1speed_I2Cmod_0_0 || ORIG_REF_NAME==testwith1speed_I2Cmod_0_0} -quiet] -quiet

# IP: bd/testwith1speed/ip/testwith1speed_Pulse_Per_Second_100_0_0/testwith1speed_Pulse_Per_Second_100_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testwith1speed_Pulse_Per_Second_100_0_0 || ORIG_REF_NAME==testwith1speed_Pulse_Per_Second_100_0_0} -quiet] -quiet

# IP: bd/testwith1speed/ip/testwith1speed_Read1_100MHZ_0_0/testwith1speed_Read1_100MHZ_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testwith1speed_Read1_100MHZ_0_0 || ORIG_REF_NAME==testwith1speed_Read1_100MHZ_0_0} -quiet] -quiet

# IP: bd/testwith1speed/ip/testwith1speed_RW_ROUTER_100MHZ_0_0/testwith1speed_RW_ROUTER_100MHZ_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testwith1speed_RW_ROUTER_100MHZ_0_0 || ORIG_REF_NAME==testwith1speed_RW_ROUTER_100MHZ_0_0} -quiet] -quiet

# IP: bd/testwith1speed/ip/testwith1speed_Switchmod_0_0/testwith1speed_Switchmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testwith1speed_Switchmod_0_0 || ORIG_REF_NAME==testwith1speed_Switchmod_0_0} -quiet] -quiet

# IP: bd/testwith1speed/ip/testwith1speed_TC_distributor_0_0/testwith1speed_TC_distributor_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testwith1speed_TC_distributor_0_0 || ORIG_REF_NAME==testwith1speed_TC_distributor_0_0} -quiet] -quiet

# IP: bd/testwith1speed/ip/testwith1speed_TM_packet_sender_0_0/testwith1speed_TM_packet_sender_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testwith1speed_TM_packet_sender_0_0 || ORIG_REF_NAME==testwith1speed_TM_packet_sender_0_0} -quiet] -quiet

# IP: bd/testwith1speed/ip/testwith1speed_UART_TX_100MHZ_0_0/testwith1speed_UART_TX_100MHZ_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testwith1speed_UART_TX_100MHZ_0_0 || ORIG_REF_NAME==testwith1speed_UART_TX_100MHZ_0_0} -quiet] -quiet

# IP: bd/testwith1speed/ip/testwith1speed_UART_RX_100MHZ_0_0/testwith1speed_UART_RX_100MHZ_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testwith1speed_UART_RX_100MHZ_0_0 || ORIG_REF_NAME==testwith1speed_UART_RX_100MHZ_0_0} -quiet] -quiet

# IP: bd/testwith1speed/ip/testwith1speed_UART_RX_100MHZ_1_0/testwith1speed_UART_RX_100MHZ_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testwith1speed_UART_RX_100MHZ_1_0 || ORIG_REF_NAME==testwith1speed_UART_RX_100MHZ_1_0} -quiet] -quiet

# IP: bd/testwith1speed/ip/testwith1speed_HTR_controller_0_0/testwith1speed_HTR_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testwith1speed_HTR_controller_0_0 || ORIG_REF_NAME==testwith1speed_HTR_controller_0_0} -quiet] -quiet

# IP: bd/testwith1speed/ip/testwith1speed_HTR_CALC_0_0/testwith1speed_HTR_CALC_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testwith1speed_HTR_CALC_0_0 || ORIG_REF_NAME==testwith1speed_HTR_CALC_0_0} -quiet] -quiet

# IP: bd/testwith1speed/ip/testwith1speed_HTR_controller_1_0/testwith1speed_HTR_controller_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testwith1speed_HTR_controller_1_0 || ORIG_REF_NAME==testwith1speed_HTR_controller_1_0} -quiet] -quiet

# IP: bd/testwith1speed/ip/testwith1speed_RESTART_mod_0_0/testwith1speed_RESTART_mod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testwith1speed_RESTART_mod_0_0 || ORIG_REF_NAME==testwith1speed_RESTART_mod_0_0} -quiet] -quiet

# IP: bd/testwith1speed/ip/testwith1speed_RAD_formatter_0_0/testwith1speed_RAD_formatter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testwith1speed_RAD_formatter_0_0 || ORIG_REF_NAME==testwith1speed_RAD_formatter_0_0} -quiet] -quiet

# IP: bd/testwith1speed/ip/testwith1speed_UART_RX_100MHZ_2_0/testwith1speed_UART_RX_100MHZ_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testwith1speed_UART_RX_100MHZ_2_0 || ORIG_REF_NAME==testwith1speed_UART_RX_100MHZ_2_0} -quiet] -quiet

# IP: bd/testwith1speed/ip/testwith1speed_Write_without_fail_1_0_0/testwith1speed_Write_without_fail_1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testwith1speed_Write_without_fail_1_0_0 || ORIG_REF_NAME==testwith1speed_Write_without_fail_1_0_0} -quiet] -quiet

# XDC: c:/GitHub/GLITCH-Software/FPGA/PCB/PCB_Test1_With1Speed/PCB_Test1_With1Speed.gen/sources_1/bd/testwith1speed/testwith1speed_ooc.xdc
