# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# Block Designs: bd/Main_Blocks/Main_Blocks.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_Blocks || ORIG_REF_NAME==Main_Blocks} -quiet] -quiet

# IP: bd/Main_Blocks/ip/Main_Blocks_sram_ctrl_0_0/Main_Blocks_sram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_Blocks_sram_ctrl_0_0 || ORIG_REF_NAME==Main_Blocks_sram_ctrl_0_0} -quiet] -quiet

# IP: bd/Main_Blocks/ip/Main_Blocks_Switchmod_0_0/Main_Blocks_Switchmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_Blocks_Switchmod_0_0 || ORIG_REF_NAME==Main_Blocks_Switchmod_0_0} -quiet] -quiet

# IP: bd/Main_Blocks/ip/Main_Blocks_UART_TXmod_0_0/Main_Blocks_UART_TXmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_Blocks_UART_TXmod_0_0 || ORIG_REF_NAME==Main_Blocks_UART_TXmod_0_0} -quiet] -quiet

# XDC: c:/GitHub/GLITCH-Software/FPGA/I2C/SRAM_Breadbord_Test/SRAM_Breadbord_Test.gen/sources_1/bd/Main_Blocks/Main_Blocks_ooc.xdc
