# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# Block Designs: bd/fetch_gnns_1/fetch_gnns_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fetch_gnns_1 || ORIG_REF_NAME==fetch_gnns_1} -quiet] -quiet

# IP: bd/fetch_gnns_1/ip/fetch_gnns_1_Switchmod_0_0/fetch_gnns_1_Switchmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fetch_gnns_1_Switchmod_0_0 || ORIG_REF_NAME==fetch_gnns_1_Switchmod_0_0} -quiet] -quiet

# IP: bd/fetch_gnns_1/ip/fetch_gnns_1_UART_RXmod_0_0/fetch_gnns_1_UART_RXmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fetch_gnns_1_UART_RXmod_0_0 || ORIG_REF_NAME==fetch_gnns_1_UART_RXmod_0_0} -quiet] -quiet

# IP: bd/fetch_gnns_1/ip/fetch_gnns_1_GNSS_Fetcher_mod_0_0/fetch_gnns_1_GNSS_Fetcher_mod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fetch_gnns_1_GNSS_Fetcher_mod_0_0 || ORIG_REF_NAME==fetch_gnns_1_GNSS_Fetcher_mod_0_0} -quiet] -quiet

# IP: bd/fetch_gnns_1/ip/fetch_gnns_1_GNSS_Sender_0_0/fetch_gnns_1_GNSS_Sender_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fetch_gnns_1_GNSS_Sender_0_0 || ORIG_REF_NAME==fetch_gnns_1_GNSS_Sender_0_0} -quiet] -quiet

# IP: bd/fetch_gnns_1/ip/fetch_gnns_1_Packet_chopper_0_0/fetch_gnns_1_Packet_chopper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fetch_gnns_1_Packet_chopper_0_0 || ORIG_REF_NAME==fetch_gnns_1_Packet_chopper_0_0} -quiet] -quiet

# IP: bd/fetch_gnns_1/ip/fetch_gnns_1_UART_TXmod_0_0/fetch_gnns_1_UART_TXmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fetch_gnns_1_UART_TXmod_0_0 || ORIG_REF_NAME==fetch_gnns_1_UART_TXmod_0_0} -quiet] -quiet

# XDC: c:/GitHub/GLITCH-Software/FPGA/UART/GNSS_Fetcher_Test/GNSS_Fetcher_Test.gen/sources_1/bd/fetch_gnns_1/fetch_gnns_1_ooc.xdc
