# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# Block Designs: bd/Func_test1/Func_test1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Func_test1 || ORIG_REF_NAME==Func_test1} -quiet] -quiet

# IP: bd/Func_test1/ip/Func_test1_BF_Data_Collector_Dr_0_0/Func_test1_BF_Data_Collector_Dr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Func_test1_BF_Data_Collector_Dr_0_0 || ORIG_REF_NAME==Func_test1_BF_Data_Collector_Dr_0_0} -quiet] -quiet

# IP: bd/Func_test1/ip/Func_test1_Read6_0_0/Func_test1_Read6_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Func_test1_Read6_0_0 || ORIG_REF_NAME==Func_test1_Read6_0_0} -quiet] -quiet

# IP: bd/Func_test1/ip/Func_test1_Write6_0_0/Func_test1_Write6_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Func_test1_Write6_0_0 || ORIG_REF_NAME==Func_test1_Write6_0_0} -quiet] -quiet

# IP: bd/Func_test1/ip/Func_test1_RW_ROUTER4_0_0/Func_test1_RW_ROUTER4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Func_test1_RW_ROUTER4_0_0 || ORIG_REF_NAME==Func_test1_RW_ROUTER4_0_0} -quiet] -quiet

# IP: bd/Func_test1/ip/Func_test1_Switchmod_0_0/Func_test1_Switchmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Func_test1_Switchmod_0_0 || ORIG_REF_NAME==Func_test1_Switchmod_0_0} -quiet] -quiet

# IP: bd/Func_test1/ip/Func_test1_BF_formatter_0_0/Func_test1_BF_formatter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Func_test1_BF_formatter_0_0 || ORIG_REF_NAME==Func_test1_BF_formatter_0_0} -quiet] -quiet

# IP: bd/Func_test1/ip/Func_test1_I2C_full_sensor_data_0_0/Func_test1_I2C_full_sensor_data_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Func_test1_I2C_full_sensor_data_0_0 || ORIG_REF_NAME==Func_test1_I2C_full_sensor_data_0_0} -quiet] -quiet

# IP: bd/Func_test1/ip/Func_test1_TM_packet_sender_0_0/Func_test1_TM_packet_sender_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Func_test1_TM_packet_sender_0_0 || ORIG_REF_NAME==Func_test1_TM_packet_sender_0_0} -quiet] -quiet

# IP: bd/Func_test1/ip/Func_test1_UART_TXmod_0_0/Func_test1_UART_TXmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Func_test1_UART_TXmod_0_0 || ORIG_REF_NAME==Func_test1_UART_TXmod_0_0} -quiet] -quiet

# IP: bd/Func_test1/ip/Func_test1_I2Cmod_0_0/Func_test1_I2Cmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Func_test1_I2Cmod_0_0 || ORIG_REF_NAME==Func_test1_I2Cmod_0_0} -quiet] -quiet

# XDC: c:/GitHub/GLITCH-Software/FPGA/SRAM TESTING/SRAM_Breadboard_Test6/SRAM_Breadboard_Test6.gen/sources_1/bd/Func_test1/Func_test1_ooc.xdc
