# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# Block Designs: bd/Error_Test/Error_Test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Error_Test || ORIG_REF_NAME==Error_Test} -quiet] -quiet

# IP: bd/Error_Test/ip/Error_Test_Read_WithError_0_0/Error_Test_Read_WithError_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Error_Test_Read_WithError_0_0 || ORIG_REF_NAME==Error_Test_Read_WithError_0_0} -quiet] -quiet

# IP: bd/Error_Test/ip/Error_Test_RW_ROUTER_0_0/Error_Test_RW_ROUTER_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Error_Test_RW_ROUTER_0_0 || ORIG_REF_NAME==Error_Test_RW_ROUTER_0_0} -quiet] -quiet

# IP: bd/Error_Test/ip/Error_Test_Write_addresses_With_0_0/Error_Test_Write_addresses_With_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Error_Test_Write_addresses_With_0_0 || ORIG_REF_NAME==Error_Test_Write_addresses_With_0_0} -quiet] -quiet

# IP: bd/Error_Test/ip/Error_Test_Switchmod_0_0/Error_Test_Switchmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Error_Test_Switchmod_0_0 || ORIG_REF_NAME==Error_Test_Switchmod_0_0} -quiet] -quiet

# IP: bd/Error_Test/ip/Error_Test_UART_TXmod_0_0/Error_Test_UART_TXmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Error_Test_UART_TXmod_0_0 || ORIG_REF_NAME==Error_Test_UART_TXmod_0_0} -quiet] -quiet

# XDC: c:/GitHub/GLITCH-Software/FPGA/SRAM TESTING/SRAM_Breadboard_Test3/SRAM_Breadboard_Test3.gen/sources_1/bd/Error_Test/Error_Test_ooc.xdc
