# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# Block Designs: bd/Error_correction/Error_correction.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Error_correction || ORIG_REF_NAME==Error_correction} -quiet] -quiet

# IP: bd/Error_correction/ip/Error_correction_Read4_0_0/Error_correction_Read4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Error_correction_Read4_0_0 || ORIG_REF_NAME==Error_correction_Read4_0_0} -quiet] -quiet

# IP: bd/Error_correction/ip/Error_correction_RW_ROUTER4_0_0/Error_correction_RW_ROUTER4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Error_correction_RW_ROUTER4_0_0 || ORIG_REF_NAME==Error_correction_RW_ROUTER4_0_0} -quiet] -quiet

# IP: bd/Error_correction/ip/Error_correction_Switchmod_0_0/Error_correction_Switchmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Error_correction_Switchmod_0_0 || ORIG_REF_NAME==Error_correction_Switchmod_0_0} -quiet] -quiet

# IP: bd/Error_correction/ip/Error_correction_UART_TXmod_0_0/Error_correction_UART_TXmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Error_correction_UART_TXmod_0_0 || ORIG_REF_NAME==Error_correction_UART_TXmod_0_0} -quiet] -quiet

# IP: bd/Error_correction/ip/Error_correction_Write4_0_0/Error_correction_Write4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Error_correction_Write4_0_0 || ORIG_REF_NAME==Error_correction_Write4_0_0} -quiet] -quiet

# XDC: c:/GitHub/GLITCH-Software/FPGA/SRAM TESTING/SRAM_Breadboard_Test4/SRAM_Breadboard_Test4.gen/sources_1/bd/Error_correction/Error_correction_ooc.xdc
