#ifndef PACKET_SIZES_H
#define PACKET_SIZES_H

#include "sdkconfig.h"

// Calculate packet sizes dynamically based on config values
#define HOUSEKEEPING_PACKET_SIZE_CALCULATED ((CONFIG_ID_SIZE + CONFIG_SEQ_COUNTER_SIZE + CONFIG_RTC_SIZE + CONFIG_GNSS_SIZE + CONFIG_TEMP_SIZE + CONFIG_ALT_SIZE + CONFIG_CRC_SIZE + 7) / 8)
#define BITFLIP_PACKET_SIZE_CALCULATED ((CONFIG_ID_SIZE + CONFIG_SEQ_COUNTER_SIZE + CONFIG_RTC_SIZE + CONFIG_BITFLIP_SIZE + CONFIG_CRC_SIZE + 7) / 8)
#define RADIATION_PACKET_SIZE_CALCULATED ((CONFIG_ID_SIZE + CONFIG_SEQ_COUNTER_SIZE + CONFIG_RTC_SIZE + CONFIG_RADIATION_SIZE + CONFIG_CRC_SIZE + 7) / 8)
#define ACKNOWLEDGEMENT_PACKET_SIZE_CALCULATED ((CONFIG_ID_SIZE + CONFIG_SEQ_COUNTER_SIZE + CONFIG_RTC_SIZE + CONFIG_TC_SIZE + CONFIG_CRC_SIZE + 7) / 8)

// Verify that the configured values match the calculated ones
#if CONFIG_HOUSEKEEPING_PACKET_SIZE != HOUSEKEEPING_PACKET_SIZE_CALCULATED
#warning "CONFIG_HOUSEKEEPING_PACKET_SIZE does not match calculated value"
#endif

#if CONFIG_BITFLIP_PACKET_SIZE != BITFLIP_PACKET_SIZE_CALCULATED
#warning "CONFIG_BITFLIP_PACKET_SIZE does not match calculated value"
#endif

#if CONFIG_RADIATION_PACKET_SIZE != RADIATION_PACKET_SIZE_CALCULATED
#warning "CONFIG_RADIATION_PACKET_SIZE does not match calculated value"
#endif

#if CONFIG_ACKNOWLEDGEMENT_PACKET_SIZE != ACKNOWLEDGEMENT_PACKET_SIZE_CALCULATED
#warning "CONFIG_ACKNOWLEDGEMENT_PACKET_SIZE does not match calculated value"
#endif

#endif // PACKET_SIZES_H
