# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# Block Designs: bd/simple_PCB_test/simple_PCB_test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simple_PCB_test || ORIG_REF_NAME==simple_PCB_test} -quiet] -quiet

# IP: bd/simple_PCB_test/ip/simple_PCB_test_SRAM_controller_0_0/simple_PCB_test_SRAM_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simple_PCB_test_SRAM_controller_0_0 || ORIG_REF_NAME==simple_PCB_test_SRAM_controller_0_0} -quiet] -quiet

# IP: bd/simple_PCB_test/ip/simple_PCB_test_Switchmod_0_0/simple_PCB_test_Switchmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simple_PCB_test_Switchmod_0_0 || ORIG_REF_NAME==simple_PCB_test_Switchmod_0_0} -quiet] -quiet

# IP: bd/simple_PCB_test/ip/simple_PCB_test_TC_distributor_0_0/simple_PCB_test_TC_distributor_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simple_PCB_test_TC_distributor_0_0 || ORIG_REF_NAME==simple_PCB_test_TC_distributor_0_0} -quiet] -quiet

# IP: bd/simple_PCB_test/ip/simple_PCB_test_TM_packet_sender_0_0/simple_PCB_test_TM_packet_sender_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simple_PCB_test_TM_packet_sender_0_0 || ORIG_REF_NAME==simple_PCB_test_TM_packet_sender_0_0} -quiet] -quiet

# IP: bd/simple_PCB_test/ip/simple_PCB_test_UART_TX_100MHZ_0_0/simple_PCB_test_UART_TX_100MHZ_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simple_PCB_test_UART_TX_100MHZ_0_0 || ORIG_REF_NAME==simple_PCB_test_UART_TX_100MHZ_0_0} -quiet] -quiet

# IP: bd/simple_PCB_test/ip/simple_PCB_test_UART_RX_100MHZ_0_0/simple_PCB_test_UART_RX_100MHZ_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simple_PCB_test_UART_RX_100MHZ_0_0 || ORIG_REF_NAME==simple_PCB_test_UART_RX_100MHZ_0_0} -quiet] -quiet

# IP: bd/simple_PCB_test/ip/simple_PCB_test_Switchmod_1_0/simple_PCB_test_Switchmod_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simple_PCB_test_Switchmod_1_0 || ORIG_REF_NAME==simple_PCB_test_Switchmod_1_0} -quiet] -quiet

# XDC: c:/GitHub/GLITCH-Software/FPGA/PCB/PCB_simple_SRAM_test/PCB_simple_SRAM_test.gen/sources_1/bd/simple_PCB_test/simple_PCB_test_ooc.xdc
