# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# Block Designs: bd/Alg_Test1/Alg_Test1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Alg_Test1 || ORIG_REF_NAME==Alg_Test1} -quiet] -quiet

# IP: bd/Alg_Test1/ip/Alg_Test1_Write_All_Adresses_0_0/Alg_Test1_Write_All_Adresses_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Alg_Test1_Write_All_Adresses_0_0 || ORIG_REF_NAME==Alg_Test1_Write_All_Adresses_0_0} -quiet] -quiet

# IP: bd/Alg_Test1/ip/Alg_Test1_Read_When_Push_0_0/Alg_Test1_Read_When_Push_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Alg_Test1_Read_When_Push_0_0 || ORIG_REF_NAME==Alg_Test1_Read_When_Push_0_0} -quiet] -quiet

# IP: bd/Alg_Test1/ip/Alg_Test1_UART_TXmod_0_0/Alg_Test1_UART_TXmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Alg_Test1_UART_TXmod_0_0 || ORIG_REF_NAME==Alg_Test1_UART_TXmod_0_0} -quiet] -quiet

# IP: bd/Alg_Test1/ip/Alg_Test1_Switchmod_0_0/Alg_Test1_Switchmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Alg_Test1_Switchmod_0_0 || ORIG_REF_NAME==Alg_Test1_Switchmod_0_0} -quiet] -quiet

# IP: bd/Alg_Test1/ip/Alg_Test1_RW_ROUTER_0_0/Alg_Test1_RW_ROUTER_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Alg_Test1_RW_ROUTER_0_0 || ORIG_REF_NAME==Alg_Test1_RW_ROUTER_0_0} -quiet] -quiet

# XDC: c:/GitHub/GLITCH-Software/FPGA/SRAM TESTING/SRAM_Breadbord_Test_2/SRAM_Breadbord_Test_2.gen/sources_1/bd/Alg_Test1/Alg_Test1_ooc.xdc
