# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# Block Designs: bd/Program_MCU/Program_MCU.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Program_MCU || ORIG_REF_NAME==Program_MCU} -quiet] -quiet

# IP: bd/Program_MCU/ip/Program_MCU_UART_RXmod_0_0/Program_MCU_UART_RXmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Program_MCU_UART_RXmod_0_0 || ORIG_REF_NAME==Program_MCU_UART_RXmod_0_0} -quiet] -quiet

# IP: bd/Program_MCU/ip/Program_MCU_UART_TXmod_0_0/Program_MCU_UART_TXmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Program_MCU_UART_TXmod_0_0 || ORIG_REF_NAME==Program_MCU_UART_TXmod_0_0} -quiet] -quiet

# IP: bd/Program_MCU/ip/Program_MCU_UART_RXmod_1_0/Program_MCU_UART_RXmod_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Program_MCU_UART_RXmod_1_0 || ORIG_REF_NAME==Program_MCU_UART_RXmod_1_0} -quiet] -quiet

# IP: bd/Program_MCU/ip/Program_MCU_UART_TXmod_1_0/Program_MCU_UART_TXmod_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Program_MCU_UART_TXmod_1_0 || ORIG_REF_NAME==Program_MCU_UART_TXmod_1_0} -quiet] -quiet

# XDC: c:/GitHub/GLITCH-Software/FPGA/BIG PICTURE STUFF/Program_MCU/Program_MCU.gen/sources_1/bd/Program_MCU/Program_MCU_ooc.xdc
